apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
   name: test-eks
   region: eu-west-2

autoModeConfig:
    # defaults to false
    enabled: true
    # optional, defaults to [general-purpose, system].
    # To disable creation of nodePools, set it to the empty array ([]).
    nodePools: [general-purpose, system]

iam:
  withOIDC: true
